version: "3.9"
services:
  go_rss_service:
    build:
      dockerfile: ./docker/service/Dockerfile
      context: .
      target: dev
    volumes:
      - ./codebase:/opt/go_rss_service/api
    environment:
      API_SERVER_ADDR: ":3000"
      AMQP_SERVER_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@127.0.0.1:15672/"
    ports:
      - "${APP_PORT}:3000"