version: "3.9"
services:
  go_rss_service:
    build:
      dockerfile: ./docker/service/Dockerfile
      context: .
      target: dev
    volumes:
      - ./codebase:/opt/go_rss_service/api
    environment:
      API_SERVER_ADDR: ":3000"
    ports:
      - "${APP_PORT}:3000"